export enum ROLES {
  ADMIN = 'ADMIN',
  INDIVIDUAL_USER = 'INDIVIDUAL_USER',
  STARTUP = 'STARTUP',
}

export enum INDIVIDUAL_USER_TYPE {
  SKILLED_INDIVIDUAL = 'SKILLED_INDIVIDUAL',
  EXPERT = 'EXPERT',
  MENTOR = 'MENTOR',
  ANGLE_INVESTOR = 'ANGLE_INVESTOR',
}

export enum EmploymentType {
  FULL_TILE = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  FREELANCE = 'FREELANCE',
  INTERNSHIP = 'INTERNSHIP',
  TRAINEE = 'TRAINEE',
}

export enum STARTUP_EXPERIENCE {
  YES = 'yes',
  NO = 'no',
}
